### ISSUE TITLE
Add support for `.env` config files

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#110]
Use the [golang env module](https://github.com/caarlos0/env) to validate `.env` configuration files

**Comment by Sairaviteja27** [comment]
@kehoecj I am new to this repo. Could you assign this to me. I am eager to give it a try

**Comment by kehoecj** [comment]
> @kehoecj I am new to this repo. Could you assign this to me. I am eager to give it a try

Glad to have you! Assigned it to you

**Comment by Sairaviteja27** [comment]
@kehoecj, I've evaluated [the module](https://github.com/caarlos0/env), designed for parsing env variables into a struct. However, I think it doesn't seem to suit our specific needs. I recommend considering more widely adopted libraries like [viper](https://github.com/spf13/viper) or [godotenv](https://github.com/joho/godotenv). Alternatively, we could try implementing a custom solution using regex.

**Comment by kehoecj** [comment]
>However, I think it doesn't seem to suit our specific needs

What specifically is deficient? Most of the validator implementations attempt to parse the config file into a struct. Viper and godotenv seem more geared toward loading environment variables for runtime use.

**Comment by GeraltO18** [comment]
Hi @kehoecj, I am giving it a try. I have debugged and found where to add this functionality. will raise a PR soon.

**Comment by GeraltO18** [comment]
Also, the library, that you have suggested doesn't have a straightforward method to validate an env file. it does have a parse method which to parse the file and load the value, but we need to provide the interface to get content. since you are trying to just validate, we might not know the exact schema of the file. So how about writing the validation logic. we can check the syntax structure using regex for key=value and comment starting with #.

**Comment by parkerstafford** [comment]
Is anyone working on this? Is this something desired?
