### ISSUE TITLE
[FEATURE REQUEST] Add support for glob patterns

### ISSUE THREAD

**Issue by olunusib** [Boeing/config-file-validator#165]
**Description**

Add support for glob patterns to allow more flexible and precise file matching

**Examples:**

``` bash
validator "**/*.json" # validate all json files

validator "config/**/*_prod.yaml"  # validate only YAML files with '_prod' in their name within the config directory
```

**Comment by kehoecj** [comment]
@olunusib Great suggestion! Just to make sure I'm understanding your first example (`validator "**/*.json" # validate all json files`) how does that differ from the functionality today?

**Comment by ccoVeille** [comment]
I would suggest using [doublestar](https://github.com/bmatcuk/doublestar)

**Comment by olunusib** [comment]
True, the first example is already doable with an extra flag

**Comment by kehoecj** [comment]
@anya004 Looking at this more there's actually not a great way to target only one file type so I think the glob pattern makes sense. In order to target only a single config type you'd have to exclude all available types like this `validator --exclude-type=xml,yaml,...`. Looking at it further we also don't provide a list of types that are visible outside of the code. I'll create a separate issue for that.

**Comment by timwehrle** [comment]
@kehoecj I can look into it. Would integrate the doublestar library mentioned above.

**Comment by anya004** [comment]
@timwehrle I started looking into it and will have a PR ready today!

**Comment by timwehrle** [comment]
@anya004 If you need additional help, reach out :)
