### ISSUE TITLE
Discussion: Improve CLI experience

### ISSUE THREAD

**Issue by ravsii** [Boeing/config-file-validator#17]
### Use of os.Args[]
It's recommended to use os.Args[] instead of flag parsing libraries for mandatory arguments like search-path. To achieve this, one option is to modify the command to accept `./validator .` instead of `./validator -search-path .`.

### Third-party flag parsers
Including third-party flag parsers could make it easier for users to understand flags since they provide prettier documentation and support for both long and short flags (e.g., `-d` for `--exclude-dirs`). Some examples are:
1. [go-flags](https://github.com/jessevdk/go-flags)
2. [cobra](https://github.com/spf13/cobra) (although it might be an overkill for this case)

### Refactoring flag parsing
While working on issue #16, I noticed that the flags are hardcoded, which can be problematic if more flags are added in the future. The `getCLIValues` and `getFlags` functions will grow bigger and bigger. In my opinion, using the options pattern would be an ideal solution in this case.

**Comment by kehoecj** [comment]
>It's recommended to use os.Args[] instead of flag parsing libraries for mandatory arguments like search-path. To achieve this, one option is to modify the command to accept ./validator . instead of ./validator -search-path ..

I agree with this - I had been thinking of writing an issue on it but forgot to include it in the initial population

>Third-party flag parsers

We had avoided 3rd party flag parsers initially because they felt heavy and added a lot of boilerplate. I'll check out your suggested parsers and see what those look like

>Refactoring flag parsing

In 2 MR's alone we have now added 2 options so I agree it's a good time to think about a more extensible solution

**Comment by kehoecj** [comment]
@ravsii I took a shot at improving the CLI and Finder API's in #33

**Comment by kehoecj** [comment]
Going to close this with the changes in #33
